# Site settings
title: CYberMouflons Theme
description: >- # site description
  This is the official CYberMouflons Jekyll theme
lang: en-US # default lang
timezone: Europe/Athens
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/cybermouflons/ # site repo [optional]
mode: dark # default theme "dark" | "light"

intro:
  heading: 
    primary: CYber
    secondary: Mouflons

cybermouflons:
  logo_dark: /assets/img/logo_dark512x512.png
  logo_light: /assets/img/logo_light512x512.png
  twitter: cybermouflons
  github: cybermouflons
  email: info@cybermouflons.com

# URL settings
url: "/" #
baseurl: 
permalink: /:title/
google_analytics: "UA-148838738-1"
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: CYberMouflons
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - cybermouflons.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

